In [13]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import math

In [2]:
df=pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [3]:
df.experience=df.experience.fillna(0)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          0                    8.0                           9      50000
1          0                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [4]:
word_to_num_mapping = {
    'one': 1,
    'two': 2,
    'three': 3,
    'four': 4,
    'five': 5,
    'six':6,
    'seven':7,
    'eleven':11,
    'ten':10
}


In [5]:
df.experience = df.experience.map(word_to_num_mapping)


In [6]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [7]:
df.experience=df.experience.fillna(0)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [11]:
df['test_score(out of 10)'].mean()

7.857142857142857

In [17]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].mean())
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0               8.000000                           9      50000
1         0.0               8.000000                           6      45000
2         5.0               6.000000                           7      60000
3         2.0              10.000000                          10      65000
4         7.0               9.000000                           6      70000
5         3.0               7.000000                          10      62000
6        10.0               7.857143                           7      72000
7        11.0               7.000000                           8      80000

In [18]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].apply(lambda x: math.ceil(x))

In [19]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                      8                           9      50000
1         0.0                      8                           6      45000
2         5.0                      6                           7      60000
3         2.0                     10                          10      65000
4         7.0                      9                           6      70000
5         3.0                      7                          10      62000
6        10.0                      8                           7      72000
7        11.0                      7                           8      80000

In [22]:
reg=linear_model.LinearRegression()
reg.fit(df.drop('salary($)', axis='columns'), df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [23]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [24]:
reg.predict([[12,10,10]])

array([92002.18340611])

In [25]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [26]:
reg.intercept_

17737.26346433771